/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quicklist;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author pabloycesar
 */
public class PantallaDeIngreso extends javax.swing.JFrame {

    /**
     * Creates new form PantallaDeIngreso
     */
    public PantallaDeIngreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        Panel_Principal = new javax.swing.JPanel();
        Panel_Titulo = new javax.swing.JPanel();
        Label_Titulo = new javax.swing.JLabel();
        Panel_Usuario = new javax.swing.JPanel();
        Espacio_Izquierdo_Usuario = new javax.swing.JLabel();
        Label_Usuario = new javax.swing.JLabel();
        TextField_Usuario = new javax.swing.JTextField();
        Espacio_Derecho_Usuario = new javax.swing.JLabel();
        Panel_Contraseña = new javax.swing.JPanel();
        Espacio_Izquierdo_Contrasena = new javax.swing.JLabel();
        Label_Contrasena = new javax.swing.JLabel();
        TextField_Contrasena = new javax.swing.JTextField();
        Espacio_Derecho_Contrasena = new javax.swing.JLabel();
        Panel_TipoDeUsuario = new javax.swing.JPanel();
        Espacio_Izquierdo_TipoDeUsuario = new javax.swing.JLabel();
        Label_TipoDeUsuario = new javax.swing.JLabel();
        ComboBox_TipoDeUsuario = new javax.swing.JComboBox();
        Espacio_Derecho_TipoDeUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Panel_Principal.setBackground(new java.awt.Color(0, 204, 0));
        Panel_Principal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 10));

        Panel_Titulo.setBackground(new java.awt.Color(0, 153, 0));
        Panel_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Label_Titulo.setBackground(new java.awt.Color(0, 102, 0));
        Label_Titulo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 70)); // NOI18N
        Label_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Label_Titulo.setText("QuickList");
        Label_Titulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout Panel_TituloLayout = new javax.swing.GroupLayout(Panel_Titulo);
        Panel_Titulo.setLayout(Panel_TituloLayout);
        Panel_TituloLayout.setHorizontalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_TituloLayout.setVerticalGroup(
            Panel_TituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_TituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Panel_Usuario.setBackground(new java.awt.Color(0, 204, 0));
        Panel_Usuario.setLayout(new java.awt.GridLayout(1, 0));
        Panel_Usuario.add(Espacio_Izquierdo_Usuario);

        Label_Usuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Label_Usuario.setForeground(new java.awt.Color(0, 102, 0));
        Label_Usuario.setText("             Usuario:");
        Panel_Usuario.add(Label_Usuario);

        TextField_Usuario.setBackground(new java.awt.Color(0, 153, 0));
        TextField_Usuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        TextField_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        TextField_Usuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextField_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_UsuarioActionPerformed(evt);
            }
        });
        Panel_Usuario.add(TextField_Usuario);
        Panel_Usuario.add(Espacio_Derecho_Usuario);

        Panel_Contraseña.setBackground(new java.awt.Color(0, 204, 0));
        Panel_Contraseña.setLayout(new java.awt.GridLayout(1, 0));

        Espacio_Izquierdo_Contrasena.setBackground(new java.awt.Color(0, 204, 51));
        Panel_Contraseña.add(Espacio_Izquierdo_Contrasena);

        Label_Contrasena.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Label_Contrasena.setForeground(new java.awt.Color(0, 102, 0));
        Label_Contrasena.setText("       Contraseña:");
        Panel_Contraseña.add(Label_Contrasena);

        TextField_Contrasena.setBackground(new java.awt.Color(0, 153, 0));
        TextField_Contrasena.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        TextField_Contrasena.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        TextField_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_ContrasenaActionPerformed(evt);
            }
        });
        Panel_Contraseña.add(TextField_Contrasena);
        Panel_Contraseña.add(Espacio_Derecho_Contrasena);

        Panel_TipoDeUsuario.setBackground(new java.awt.Color(0, 204, 0));
        Panel_TipoDeUsuario.setLayout(new java.awt.GridLayout(1, 0));
        Panel_TipoDeUsuario.add(Espacio_Izquierdo_TipoDeUsuario);

        Label_TipoDeUsuario.setBackground(new java.awt.Color(0, 102, 0));
        Label_TipoDeUsuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        Label_TipoDeUsuario.setForeground(new java.awt.Color(0, 102, 0));
        Label_TipoDeUsuario.setText("Tipo de usuario:");
        Panel_TipoDeUsuario.add(Label_TipoDeUsuario);

        ComboBox_TipoDeUsuario.setBackground(new java.awt.Color(0, 153, 0));
        ComboBox_TipoDeUsuario.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        ComboBox_TipoDeUsuario.setForeground(new java.awt.Color(0, 102, 0));
        ComboBox_TipoDeUsuario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprendiz", "Instructor", "Administrador" }));
        ComboBox_TipoDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_TipoDeUsuarioActionPerformed(evt);
            }
        });
        Panel_TipoDeUsuario.add(ComboBox_TipoDeUsuario);
        Panel_TipoDeUsuario.add(Espacio_Derecho_TipoDeUsuario);

        jPanel1.setBackground(new java.awt.Color(0, 204, 0));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));
        jPanel1.add(jLabel1);

        jButton1.setBackground(new java.awt.Color(0, 153, 0));
        jButton1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 0));
        jButton2.setText("Registrarse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jPanel1.add(jLabel2);

        jPanel3.setBackground(new java.awt.Color(0, 204, 0));

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setText("¿ Olvidaste tu contraseña ?");
        jPanel3.add(jLabel3);

        javax.swing.GroupLayout Panel_PrincipalLayout = new javax.swing.GroupLayout(Panel_Principal);
        Panel_Principal.setLayout(Panel_PrincipalLayout);
        Panel_PrincipalLayout.setHorizontalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_Contraseña, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Panel_TipoDeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panel_PrincipalLayout.setVerticalGroup(
            Panel_PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_PrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Panel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Panel_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_TipoDeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipady = -101;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(Panel_Principal, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextField_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_UsuarioActionPerformed

    private void TextField_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_ContrasenaActionPerformed

    private void ComboBox_TipoDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_TipoDeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_TipoDeUsuarioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        if("Administrador".equals(this.ComboBox_TipoDeUsuario.getSelectedItem().toString())){
            
            Pantalla_Principal_Administrador  Pantalla_Principal_Administrador = new Pantalla_Principal_Administrador();
            Pantalla_Principal_Administrador.setLocation(this.getLocation().x,this.getLocation().y);
            Pantalla_Principal_Administrador.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaDeIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaDeIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaDeIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaDeIngreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaDeIngreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_TipoDeUsuario;
    private javax.swing.JLabel Espacio_Derecho_Contrasena;
    private javax.swing.JLabel Espacio_Derecho_TipoDeUsuario;
    private javax.swing.JLabel Espacio_Derecho_Usuario;
    private javax.swing.JLabel Espacio_Izquierdo_Contrasena;
    private javax.swing.JLabel Espacio_Izquierdo_TipoDeUsuario;
    private javax.swing.JLabel Espacio_Izquierdo_Usuario;
    private javax.swing.JLabel Label_Contrasena;
    private javax.swing.JLabel Label_TipoDeUsuario;
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JLabel Label_Usuario;
    private javax.swing.JPanel Panel_Contraseña;
    private javax.swing.JPanel Panel_Principal;
    private javax.swing.JPanel Panel_TipoDeUsuario;
    private javax.swing.JPanel Panel_Titulo;
    private javax.swing.JPanel Panel_Usuario;
    private javax.swing.JTextField TextField_Contrasena;
    private javax.swing.JTextField TextField_Usuario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables


}
